# managed-by zoomies — site:77777777-7777-4777-8777-777777777777  upstream:88888888-8888-4888-8888-888888888888
upstream zoomies_77777777_7777_4777_8777_777777777777 {
    ip_hash;
    server 10.0.2.1:8080 weight=1;
    server 10.0.2.2:8080 weight=1;
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name secure.example.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name secure.example.com;
    ssl_certificate /var/lib/zoomies/certs/secure.example.com.pem;
    ssl_certificate_key /var/lib/zoomies/certs/secure.example.com.key;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_pass http://zoomies_77777777_7777_4777_8777_777777777777;
    }
}
